name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
    uses: adamhl8/configs/.github/workflows/release.yml@main
    secrets: inherit

  tag:
    needs: release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Get release tag
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

  build:
    needs: tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: bun-windows-x64
            artifact: inspectarr-windows-x64.exe
          - target: bun-darwin-x64
            artifact: inspectarr-macos-x64
          - target: bun-darwin-arm64
            artifact: inspectarr-macos-arm64
          - target: bun-linux-x64-musl
            artifact: inspectarr-linux-x64
          - target: bun-linux-arm64-musl
            artifact: inspectarr-linux-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ needs.tag.outputs.tag }}

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: |
          # TODO: remove once bun 1.4.0 is released
          rm -f bun.lock #
          bun install --ignore-scripts

      - name: Build binary
        run: bun build --compile --production --minify --sourcemap --target=${{ matrix.target }} --outfile=${{ matrix.artifact }} src/index.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  publish:
    needs: [tag, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG: ${{ needs.tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ needs.tag.outputs.tag }}

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: |
          # TODO: remove once bun 1.4.0 is released
          rm -f bun.lock #
          bun install --ignore-scripts

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Attach binaries to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${TAG}" ./artifacts/* --clobber

      - name: Process package templates
        run: |
          bun ./package_templates/template-processor.ts "${TAG#v}"

      - name: Set up git
        run: |
          git config --global user.email adamhl@pm.me
          git config --global user.name "GitHub Actions"

      - name: Update homebrew tap
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          REPO="https://adamhl8:${CI_TOKEN}@github.com/adamhl8/homebrew-inspectarr.git"
          CLONE_DIR=$(mktemp -d)
          git clone --depth 1 "${REPO}" "${CLONE_DIR}"
          cp ./package_templates/homebrew/inspectarr.rb "${CLONE_DIR}/Formula/inspectarr.rb"
          cd "${CLONE_DIR}"
          git add -A
          git commit -m "${TAG}"
          git push "${REPO}"

      - name: Update scoop bucket
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          REPO="https://adamhl8:${CI_TOKEN}@github.com/adamhl8/scoop-inspectarr.git"
          CLONE_DIR=$(mktemp -d)
          git clone --depth 1 "${REPO}" "${CLONE_DIR}"
          cp ./package_templates/scoop/inspectarr.json "${CLONE_DIR}/inspectarr.json"
          cd "${CLONE_DIR}"
          git add -A
          git commit -m "${TAG}"
          git push "${REPO}"
